### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by lucasliet** [ads-usjt/Todoey#1]
irônico fazer um todo list de um aplicativo de todo list né :P

- [x] **Mover componente de input** pra fora do header @LeoGil 
- [x] Integrar **angular com api rest** @LeoGil 
- [x] Criar página de **Login e Cadastro** @DjowNathan
- [x] Implementar função de **Editar e Excluir** Todo no **Angular**
